spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/shopica
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    host: localhost
    username: manhnguyen
    password: manh130399
