spring:
  redis:
    host: redis
    port: 6379
  datasource:
    username: admin1
    password: 12345678
    url: jdbc:mysql://mysql:3306/shopica
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    host: rabbitmq
    username: manhnguyen
    password: manh130399
